### ISSUE TITLE
Combat Tracker Rewrite

### ISSUE THREAD

**Issue by aeauseth** [dmdorman/hero6e-foundryvtt#1243]
## Combat Tracker
Should test with all supported modules enabled (specifically Drag Ruler).  Run a player FireFox browser to test both GM & Player as well as FireFox support (Forge).   Keep console windows open for both to see if there are any errors/warnings.

- [X] Add single combatant. Make sure Segment 12 is expanded. Remove single combatant.
- [X] Ego: add single combatant. Change DEX to be 22.  Make sure initiative changes.  Change to use EGO.  Make sure initiative changes. Remove single combatant.
- [X] Add single combatant. Begin combat. Make sure Segment 12 is expanded. and orange borders for first combatant. Verify Initiative is [DEX/EGO].[SPD]. Remove single combatant. Combat is still active with no combatants. End combat.
- [X] Lightning Reflexes: Add 6E token with 10 DEX, 2 SPD, LR 2.  Add 5e token with 11 DEX 2 SPD, LR (all actions) 2.  Make sure Initiatives are sorted correctly.  Begin combat, make sure turn 1 and segment 12. Remove 6e LR combatant, the non-LR combatant should automatically be removed as well. Make sure segment remains 12 (segments under 12 on turn 1 are invalid). Add 6e combatant back in.  Should have 2 entries (LR and non-LR) and remain segment 12. End Combat.
- [X] Add/Delete:  Add two combatants.  Begin combat.  Advance to last combatant in segment 12.  Add a 3rd combatant.  Make sure the active combatant doesn't change.  Delete the Active combatant.  Make sure the next combatant is now active. 
 Add combatant back in.  Delete a non-active combatant. End combat. 
- [X] Change DEX: Add two combatants.  Begin combat.  Make the lower initiative combatant active. Change the lower initiative combatant's DEX to be higher and make sure initiative order changes.  The active combatant will likely change to the next token in initiative order. End combat.
- [X] Change SPD: Add two combatants.  Begin combat.  Change SPD of active combatant. End Combat.
- [X] Add/Delete/LR: Add two combatants with LR.  Begin combat.  Delete LR from one of them.  Make sure initiative tracker removed the LR entry.  Re-upload the actor with LR.  Make sure the LR entry is added.  End Combat.
